REG_SECRET_KEY="ksdjfkdnbfieiuruer8554545tf"
REG_DEBUG="True"
REG_ALLOWED_HOSTS=["127.0.0.1"]
REG_DATABASE_NAME="postgres"
REG_DATABASE_USER="postgres"
REG_DATABASE_PW=""
REG_DATABASE_HOST="localhost"
BUGSNAG_API_KEY=""
